### ISSUE TITLE
Changing the color and look of the timesquare calendar.

### ISSUE THREAD

**Issue by tonyjoseph456** [square/android-times-square#139]
I need to change the color of the customized calendar dialog to another one. I need to change the month color, year color and the date color to another color. Where should I modify the code to make the changes? I need to change the color of septemer to gray and 2014 to gray. Also the dates has to be changed to green color. Can someone please help me out???

![screenshot_2014-09-12-14-19-54](https://cloud.githubusercontent.com/assets/2456421/4247464/2e4bdf18-3a5a-11e4-9959-59e356af8ae6.jpg)

**Comment by martygeek** [comment]
I looked at dialog_customized.xml, specifically the day dividers.  
<img width="334" alt="Screen Shot 2019-05-03 at 9 21 05 AM" src="https://user-images.githubusercontent.com/1483744/57143637-e7962c00-6d84-11e9-8ccc-d719a4548cbb.png">

How can I change the UI so each day's cell/divider is a separate square rather than a shared divider between cells?
