### ISSUE TITLE
Proposal: switching unit tests to AndroidJUnit4 runner

### ISSUE THREAD

**Issue by pwittchen** [square/android-times-square#238]
Hello.

What do you think about dropping Robolectric and switching tests to AndroidJUnit4 runner with Google Truth assertions? I see that few of your other projects like Sqlbrite use this approach.

Regards,
Piotr

**Comment by JakeWharton** [comment]
The downside is those can no longer be run on the JVM as part of the build.
We have to spin up a (crappy) emulator. The reason we choose to do this on
things like SqlBrite is that we want to run against the real implementation
of Sqlite on Android. Since this library only deals with views, the
implementation of Robolectric is actually the real implementation compiled
to run on the JVM. Because of this we can be confident that it behaves like
a real device would without having to actually test on a real device.

**Comment by pwittchen** [comment]
It makes sense. Thanks for detailed reply. 
I think, this issue can be closed now.
