### ISSUE TITLE
Detecting scroll position

### ISSUE THREAD

**Issue by giacmarangoni** [square/android-times-square#346]
Hi, I really want to thank you for this awesome custom component. I'm using android-times-square inside my application. Now I'm trying to get current calendar scroll position:

` int posX = calendar.getScrollX();`
` int posY = calendar.getScrollY();`
` calendar.scrollTo(posX,posY);`

Using a listener on these two parameters, I'm getting always 0. I'd like to know if this feature will come in a next implementation.
Thank you.

**Comment by BriungRi** [comment]
Hey giacmarangoni,

When using the CalendarViewPicker library myself, I was able to duplicate your issue. I made an onScrollChangeListener() and logged the values of getScrollX() and getScrollY() and got 0 for both those values. I decided to look into the issue and this is what I found:

CalendarPickerView extends ListView, which means that CalendarPickerView's behavior for getScrollX and getScrollY is essentially the same. At first glance, it seems like getScrollX and getScrollY will give you the X and Y position of your scroll offset, but **ListView has no concept of Y scroll because the height of the entire ListView is unknown.** I'm pretty sure this is because ListView recycles items for efficiency, so it can't tell you how far down you actually are. This answer on SO does a decent job explaining the behavior: http://stackoverflow.com/a/12728123.

Even though you won't be able to use getScrollY(), there is an alternative. You can do "calendar.getFirstVisiblePosition()" to get the position of the first visible element. With the position value, you can scroll to the specific position by calling "calendar.setSelection(int position). If you need the position to be more exact than the month itself, you can call "calendar.getChildAt(int position).getTop() to get the offset of that particular child.

Hopefully this helps!

-Brian

**Comment by edenman** [comment]
Thanks @BriungRi!
