### ISSUE TITLE
Enable translation feature on exception or any hardcoded string value?

### ISSUE THREAD

**Issue by mochadwi** [square/android-times-square#414]
![screen shot 2017-12-06 at 1 56 32 pm](https://user-images.githubusercontent.com/7057959/33648614-4ffa204e-da8d-11e7-9e8f-8171326812f4.png)

Any suggestion on how to translate this?

![screen shot 2017-12-06 at 2 08 35 pm](https://user-images.githubusercontent.com/7057959/33649069-03e9cc70-da8f-11e7-8be4-2b47f420ccdf.png)

**Comment by JakeWharton** [comment]
These strings are not meant to be displayed. They're meant to crash your
app because you violated a constraint the library imposes.

If you have untrusted input you should validate the date range yourself
before calling into the library. This gives you the ability to control when
validation happens and how it is displayed as a result.

**Comment by edenman** [comment]
1) the code snippet is irrelevant: that string is never shown to the user, and should not be translated.
2) the screenshot _is_ relevant: if you want to submit a PR with a missing translation, please do!  See https://github.com/square/android-times-square/tree/master/library/src/main/res for examples

**Comment by edenman** [comment]
lol, just saw your PR
